
# CodeClimate runs an older version of RuboCop, which apparently doesn't
# understand the `AllCops` setting. So we do it The Hard Way.

Style/StringLiterals:
  Exclude:
    - Rakefile
    - prolog-services-replace_content.gemspec

Style/WordArray:
  Exclude:
    - Rakefile

Metrics/LineLength:
  Exclude:
    - Rakefile
    - prolog-services-replace_content.gemspec

Metrics/AbcSize:
  Exclude:
    - test/prolog/use_cases/propose_edit_contribution_test.rb

Metrics/MethodLength:
  Exclude:
    - test/prolog/use_cases/propose_edit_contribution_test.rb
