
AllCops:
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Max: 300
  Include:
    - 'test/**/*_test.rb'

Metrics/ModuleLength:
  Max: 300
  Include:
    - 'test/**/*_test.rb'

Style/CommentedKeyword:
  Enabled: false

# FIXME: Obsolete code style ignored courtesy of the following:

Lint/Void:
  Enabled: false
