
# CodeClimate runs an older version of RuboCop, which apparently doesn't
# understand the `AllCops` setting. So we do it The Hard Way.

Style/PercentLiteralDelimiters:
  Exclude:
    - prolog-services-replace_content.gemspec

Style/PercentQLiterals:
  Exclude:
    - prolog-services-replace_content.gemspec

Style/StringLiterals:
  Exclude:
    - Rakefile
    - prolog-services-replace_content.gemspec
    - bin/console

Style/WordArray:
  Exclude:
    - Rakefile

# 'Real' settings follow. ###################################

Metrics/AbcSize:
  Exclude:
    - test/prolog/use_cases/propose_edit_contribution_test.rb

Metrics/MethodLength:
  Exclude:
    - test/prolog/use_cases/propose_edit_contribution_test.rb
